### ISSUE TITLE
Debug missing progress bar in home

### ISSUE THREAD

**Issue by nbaehler** [brunnerant/sdp-project#178]
Currently the progress bar which should be shown when loading from the database is not shown in the `HomeQuizListFragment`.

**Comment by brunnerant** [comment]
In the end, this issue took a lot more time than planned. This is because while debugging the progress bar, I discovered some other bugs in the app. All of them were related to concurrency issues with the asynchronous services such as the database and the location. I managed to debug all of that and fix a lot of small issues overall, so that's great.
