### ISSUE TITLE
Unify the RecyclerViews

### ISSUE THREAD

**Issue by nbaehler** [brunnerant/sdp-project#67]

**Comment by brunnerant** [comment]
The goal of this issue is to unify the recycler views that we have in the application. Currently, there is a recycler view in the home activity that allows an editor to edit the list of quizzes that he has. There is another one that allows an editor to add, remove and reorder questions within a quiz.
The goal is to merge them into one generic class so that the code is more maintainable, less redundant and the style is more consistent.
